#!/usr/bin/env jake
'use strict';
/* eslint-disable no-undef */
/* eslint-disable no-console */

const knexfileTests = require('./jakelib/knexfile-test').taskList;
const migrateTests = require('./jakelib/migrate-test').taskList;

const tests = [
  ...knexfileTests,
  ...migrateTests,
];

task('default', tests, () => {
  console.log('All done.');
});
