#!/usr/bin/env bash

# Exit on error
set -e

# Directory constants
repo_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." >/dev/null 2>&1 && pwd )"
exec_dir="$( pwd )"

help_text="
Helper script to update lib/.gitignore for all .js files from .ts files.

    update_gitignore_for_tsc_output.sh COMMAND

    COMMAND:
        run:  Update lib/.gitignore file.
        help: Print this menu.

    NOTES FOR USAGE:
    1. This script is tested to work on Ubuntu 18.04 LTS.
"

gitignore_header="\
# DO NOT EDIT, GENERATED BY: scripts/update_gitignore_for_tsc_output.shx

# Do not include tsc generated type definitions
**/*.d.ts

# Do not include tsc source maps
**/*.js.map

# Do not include .js files from .ts files
"

# Main script logic
cmd="$1"

function main () {
    case "$1" in
        "run")
            printf "Generating lib/.gitignore ...\n"
            cd "$repo_dir/lib"
            ts_files="$(find . -name "*.ts" -type f | grep -v '.d.ts')"
            js_files="$(echo "$ts_files" | sed -e 's|^\./||gm' -e 's|\.ts$|\.js|gm')"
            echo "$gitignore_header$js_files" > "$repo_dir/lib/.gitignore"
            echo "DONE"
            exit 0
            ;;
        "help"|"--help"|"-h"|"")
            printf "$help_text"
            exit 0
            ;;
        *)
            printf "Unsupported command: $cmd\n"
            printf "Try running with 'help' to see supported commands.\n"
            exit 1
            ;;
    esac
}

# Start the bash app's main function
main "$cmd"
